// Regenerate the offline demo payload from the unchanged source files.
const fs = require("node:fs");
const path = require("node:path");
const names = ["inv.gds2", "nand2.gds2", "xor.gds2", "1Kpolyg.gds"];
const data = Object.fromEntries(names.map((name) => [
  name, fs.readFileSync(path.join(__dirname, name)).toString("base64"),
]));
fs.writeFileSync(path.join(__dirname, "demo-data.js"),
  `// Generated by build-demo.cjs; see README.md for provenance.\nglobalThis.GdsDemoData = Object.freeze(${JSON.stringify(data, null, 2)});\n`);
